"""Application-wide constants for incident handling and evaluation."""

INCIDENT_SLASH_COMMAND = "/incident"

EVIDENCE_COVERAGE_THRESHOLD = 0.6
GROUNDING_PASS_THRESHOLD = 1.0

CONFIDENCE_WEIGHT_EVIDENCE = 0.4
CONFIDENCE_WEIGHT_GROUNDING = 0.4
CONFIDENCE_WEIGHT_CONSISTENCY = 0.2

INCIDENT_USAGE_HINT = "/incident <service> <description>"

INVESTIGATION_ANNOUNCEMENT_TEMPLATE = (
    ":mag: Investigating *{service}* — {description}"
)

EVAL_TYPE_COVERAGE = "coverage"
EVAL_TYPE_GROUNDING = "grounding"
EVAL_TYPE_CONSISTENCY = "consistency"

APPROVAL_ACTION_APPROVE = "approve"
APPROVAL_ACTION_REJECT = "reject"
APPROVAL_ACTION_SHOW_EVIDENCE = "show_evidence"

EVIDENCE_LOOKBACK_HOURS = 2
INTEGRATION_FETCH_TIMEOUT_SECONDS = 30
RTS_LOOKBACK_DAYS = 90

EVIDENCE_FIELD_MAX_CHARS = 500
EVIDENCE_PROMPT_TOKEN_BUDGET = 6000
CHARS_PER_TOKEN_ESTIMATE = 4
